#配置api访问端口
server:
  port: 9000
#spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 101MB
#文件储存地址
filepath: D:/file/
#钉钉消息发送地址
webhook: https://oapi.dingtalk.com/robot/send?access_token=9e15605640eecb7a104818e492ec0c76fde38c0c4945849371376c0c9ff3a879
#配置mapperXml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.Model
  #开启自动转换驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.example.demo.typeHandler
#配置分页插件pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#log4j2配置文件
logging:
  config: classpath:log4j2.xml
